"use strict";

const Order = require("../models/orderModel");
const Notification = require("../models/notificationModel");
const ServiceProvider = require("../models/serviceProviderModel");
const User = require("../models/userModel");
const Razorpay = require("razorpay");
const crypto = require("crypto");
const { isValidObjectId } = require("mongoose");
const { getIO } = require("../socket");

// ─── Razorpay Instance ────────────────────────────────────────────────────────

// Instantiated once at module load; will throw clearly if keys are missing
const razorpay = new Razorpay({
  key_id: process.env.RAZORPAY_KEY_ID,
  key_secret: process.env.RAZORPAY_KEY_SECRET,
});

// ─── Constants ────────────────────────────────────────────────────────────────

const VALID_ORDER_STATUSES = [
  "pending",
  "accepted",
  "in_progress",
  "ready",
  "delivered",
  "cancelled",
];

/**
 * Strict FSM: maps each status to the only statuses it can transition into.
 * Prevents both backward moves and illegal jumps (e.g. pending → delivered).
 */
const STATUS_FSM = {
  pending: ["accepted", "cancelled"],
  accepted: ["in_progress", "cancelled"],
  in_progress: ["ready", "cancelled"],
  ready: ["delivered", "cancelled"],
  delivered: [],   // terminal
  cancelled: [],   // terminal
};

const STATUS_MESSAGES = {
  accepted: (id) => `Your order #${id} has been accepted and is being prepared.`,
  in_progress: (id) => `Your order #${id} is now in progress.`,
  ready: (id) => `Your order #${id} is ready for delivery.`,
  delivered: (id) => `Your order #${id} has been successfully delivered. Thank you!`,
  cancelled: (id) => `Your order #${id} has been cancelled.`,
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

const validateId = (id, res, label = "Resource") => {
  if (!isValidObjectId(id)) {
    res.status(400).json({ success: false, message: `Invalid ${label} ID` });
    return false;
  }
  return true;
};

/**
 * Persist a notification and emit it over Socket.IO.
 * Non-blocking — errors are logged, never bubble up to the caller.
 */
const notify = async (userId, message, orderId, type = "order") => {
  try {
    const notification = await Notification.create({ userId, orderId, type, message });
    getIO().to(userId.toString()).emit("receive-notification", notification);
  } catch (err) {
    console.error("[notify]", err.message);
  }
};

// ─── Order CRUD ───────────────────────────────────────────────────────────────

/**
 * POST /api/order/create
 * User places a new order with a selected provider.
 * orderId is auto-generated by the Order model pre-validate hook.
 * @access Private (User)
 */
exports.createOrder = async (req, res) => {
  try {
    const {
      providerId,
      services,
      pickupAddress,
      deliveryAddress,
      pickupTime,
      deliveryTime,
      amount,
      pickupLocation,
      deliveryLocation,
    } = req.body;

    const userId = req.user.id;

    // ── Required field validation ────────────────────────────────────────────
    const missing = [];
    if (!providerId) missing.push("providerId");
    if (!services?.length) missing.push("services");
    if (!pickupAddress?.trim()) missing.push("pickupAddress");
    if (!deliveryAddress?.trim()) missing.push("deliveryAddress");
    if (!pickupTime) missing.push("pickupTime");
    if (!deliveryTime) missing.push("deliveryTime");
    if (amount === undefined || amount === null) missing.push("amount");

    if (missing.length) {
      return res.status(400).json({
        success: false,
        message: `Missing required fields: ${missing.join(", ")}`,
      });
    }

    if (!isValidObjectId(providerId)) {
      return res.status(400).json({ success: false, message: "Invalid providerId" });
    }

    const parsedAmount = Number(amount);
    if (isNaN(parsedAmount) || parsedAmount <= 0) {
      return res.status(400).json({ success: false, message: "Amount must be a positive number" });
    }

    // ── Validate services array ──────────────────────────────────────────────
    for (const [i, svc] of services.entries()) {
      if (!svc.name?.trim()) {
        return res.status(400).json({ success: false, message: `Service at index ${i} is missing a name` });
      }
      if (typeof svc.quantity !== "number" || svc.quantity < 1) {
        return res.status(400).json({ success: false, message: `Service "${svc.name}" must have quantity ≥ 1` });
      }
      if (typeof svc.price !== "number" || svc.price < 0) {
        return res.status(400).json({ success: false, message: `Service "${svc.name}" must have a non-negative price` });
      }
      if (svc.customerPrice !== undefined && (typeof svc.customerPrice !== "number" || svc.customerPrice < 0)) {
        return res.status(400).json({
          success: false,
          message: `Service "${svc.name}" must have a non-negative customerPrice`,
        });
      }
      if (svc.dealerPrice !== undefined && (typeof svc.dealerPrice !== "number" || svc.dealerPrice < 0)) {
        return res.status(400).json({
          success: false,
          message: `Service "${svc.name}" must have a non-negative dealerPrice`,
        });
      }
    }

    // ── Provider checks ──────────────────────────────────────────────────────
    const provider = await ServiceProvider.findById(providerId).lean();
    if (!provider) {
      return res.status(404).json({ success: false, message: "Provider not found" });
    }
    if (!provider.isActive || provider.isApproved !== "approved") {
      return res.status(400).json({
        success: false,
        message: "This provider is not currently accepting orders",
      });
    }

    // ── Create order (orderId auto-generated by model hook) ──────────────────
    const orderData = {
      providerId,
      userId,
      services,
      pickupAddress: pickupAddress.trim(),
      deliveryAddress: deliveryAddress.trim(),
      pickupTime: new Date(pickupTime),
      deliveryTime: new Date(deliveryTime),
      amount: parsedAmount,
      status: "pending",
      paymentStatus: "pending",
    };

    // Optional geospatial fields
    if (pickupLocation?.coordinates?.length === 2) {
      orderData.pickupLocation = { type: "Point", coordinates: pickupLocation.coordinates };
    }
    if (deliveryLocation?.coordinates?.length === 2) {
      orderData.deliveryLocation = { type: "Point", coordinates: deliveryLocation.coordinates };
    }

    const order = await Order.create(orderData);

    // ── Notify provider (non-blocking) ───────────────────────────────────────
    notify(
      provider.userId,
      `You have a new order #${order.orderId} from a customer.`,
      order._id,
      "order"
    );

    return res.status(201).json({
      success: true,
      message: "Order created successfully",
      data: {
        _id: order._id,
        orderId: order.orderId,
        status: order.status,
        paymentStatus: order.paymentStatus,
        amount: order.amount,
      },
    });
  } catch (err) {
    console.error("[createOrder]", err);

    if (err.name === "ValidationError") {
      const messages = Object.values(err.errors).map((e) => e.message);
      return res.status(400).json({ success: false, message: messages.join(". ") });
    }

    return res.status(500).json({ success: false, message: "Internal server error" });
  }
};

/**
 * GET /api/order/userOrders
 * Returns the authenticated user's own orders.
 * @query page, limit, status
 * @access Private (User)
 */
exports.getUserOrders = async (req, res) => {
  try {
    const page = Math.max(1, parseInt(req.query.page, 10) || 1);
    const limit = Math.min(50, Math.max(1, parseInt(req.query.limit, 10) || 10));
    const skip = (page - 1) * limit;

    const filter = { userId: req.user.id };
    if (req.query.status && VALID_ORDER_STATUSES.includes(req.query.status)) {
      filter.status = req.query.status;
    }

    const [orders, total] = await Promise.all([
      Order.find(filter)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .populate("providerId", "name email mobile address rating")
        .lean(),
      Order.countDocuments(filter),
    ]);

    return res.status(200).json({
      success: true,
      data: orders,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
        hasNextPage: page * limit < total,
        hasPrevPage: page > 1,
      },
    });
  } catch (err) {
    console.error("[getUserOrders]", err);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
};

/**
 * GET /api/order/dhobiOrders
 * Returns the authenticated provider's own orders.
 * @query page, limit, status
 * @access Private (Dhobi)
 */
exports.getProviderOrders = async (req, res) => {
  try {
    const provider = await ServiceProvider.findOne({ userId: req.user.id })
      .select("_id")
      .lean();

    if (!provider) {
      return res.status(404).json({ success: false, message: "Provider profile not found" });
    }

    const page = Math.max(1, parseInt(req.query.page, 10) || 1);
    const limit = Math.min(50, Math.max(1, parseInt(req.query.limit, 10) || 10));
    const skip = (page - 1) * limit;

    const filter = { providerId: provider._id };
    if (req.query.status && VALID_ORDER_STATUSES.includes(req.query.status)) {
      filter.status = req.query.status;
    }

    const [orders, total] = await Promise.all([
      Order.find(filter)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .populate("userId", "name email mobile")
        .lean(),
      Order.countDocuments(filter),
    ]);

    return res.status(200).json({
      success: true,
      data: orders,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
        hasNextPage: page * limit < total,
        hasPrevPage: page > 1,
      },
    });
  } catch (err) {
    console.error("[getProviderOrders]", err);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
};

/**
 * GET /api/order/:id
 * Get a single order.
 * Users see only their own; providers see only their assigned orders; admins see all.
 * @access Private
 */
exports.getOrderDetails = async (req, res) => {
  if (!validateId(req.params.id, res, "Order")) return;

  try {
    const order = await Order.findById(req.params.id)
      .populate("userId", "name email mobile")
      .populate("providerId", "name email mobile address")
      .lean();

    if (!order) {
      return res.status(404).json({ success: false, message: "Order not found" });
    }

    // ── Authorization ────────────────────────────────────────────────────────
    const isAdmin = req.user.role === "admin";
    const isOrderOwner = order.userId?._id?.toString() === req.user.id;

    // For provider: resolve their ServiceProvider._id
    let isOrderProvider = false;
    if (req.user.role === "dhobi") {
      const provider = await ServiceProvider.findOne({ userId: req.user.id })
        .select("_id")
        .lean();
      isOrderProvider = provider?._id?.toString() === order.providerId?._id?.toString();
    }

    if (!isAdmin && !isOrderOwner && !isOrderProvider) {
      return res.status(403).json({ success: false, message: "Access denied" });
    }

    return res.status(200).json({ success: true, data: order });
  } catch (err) {
    console.error("[getOrderDetails]", err);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
};

/**
 * GET /api/order/getAllOrders
 * Admin: all orders with pagination, filters, and population.
 * @query page, limit, status, paymentStatus
 * @access Private (Admin)
 */
exports.getAllOrders = async (req, res) => {
  try {
    const page = Math.max(1, parseInt(req.query.page, 10) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));
    const skip = (page - 1) * limit;

    const filter = {};
    if (req.query.status && VALID_ORDER_STATUSES.includes(req.query.status)) {
      filter.status = req.query.status;
    }
    if (req.query.paymentStatus && ["pending", "completed", "failed", "refunded"].includes(req.query.paymentStatus)) {
      filter.paymentStatus = req.query.paymentStatus;
    }

    const [orders, total] = await Promise.all([
      Order.find(filter)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .populate("userId", "name email mobile")
        .populate("providerId", "name email mobile")
        .lean(),
      Order.countDocuments(filter),
    ]);

    return res.status(200).json({
      success: true,
      data: orders,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
        hasNextPage: page * limit < total,
        hasPrevPage: page > 1,
      },
    });
  } catch (err) {
    console.error("[getAllOrders]", err);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
};

/**
 * PATCH /api/order/:id/status
 * Update an order's status. Enforces strict FSM transitions and notifies both parties.
 * @access Private (Dhobi, Admin)
 */
exports.updateOrderStatus = async (req, res) => {
  if (!validateId(req.params.id, res, "Order")) return;

  try {
    const { status } = req.body;

    if (!status) {
      return res.status(400).json({ success: false, message: "Status is required" });
    }

    if (!VALID_ORDER_STATUSES.includes(status)) {
      return res.status(400).json({
        success: false,
        message: `Invalid status. Valid values: ${VALID_ORDER_STATUSES.join(", ")}`,
      });
    }

    const order = await Order.findById(req.params.id);
    if (!order) {
      return res.status(404).json({ success: false, message: "Order not found" });
    }

    // ── FSM transition check ─────────────────────────────────────────────────
    const allowedNext = STATUS_FSM[order.status] ?? [];
    if (!allowedNext.includes(status)) {
      return res.status(400).json({
        success: false,
        message:
          allowedNext.length
            ? `Cannot transition from "${order.status}" to "${status}". Allowed: ${allowedNext.join(", ")}`
            : `Order is already "${order.status}" and cannot be updated`,
      });
    }

    // ── Ownership check for dhobi ────────────────────────────────────────────
    if (req.user.role === "dhobi") {
      const provider = await ServiceProvider.findOne({ userId: req.user.id })
        .select("_id")
        .lean();

      if (!provider || provider._id.toString() !== order.providerId.toString()) {
        return res.status(403).json({
          success: false,
          message: "This order does not belong to your account",
        });
      }
    }

    order.status = status;
    await order.save();

    // ── Notify customer ──────────────────────────────────────────────────────
    const customerMsg = STATUS_MESSAGES[status]?.(order.orderId)
      ?? `Your order #${order.orderId} has been updated to: ${status}`;
    notify(order.userId, customerMsg, order._id, "order");

    // ── Notify provider if customer/admin cancels ────────────────────────────
    if (status === "cancelled" && req.user.role !== "dhobi") {
      const provider = await ServiceProvider.findById(order.providerId).select("userId").lean();
      if (provider?.userId) {
        notify(
          provider.userId,
          `Order #${order.orderId} has been cancelled.`,
          order._id,
          "order"
        );
      }
    }

    return res.status(200).json({
      success: true,
      message: "Order status updated successfully",
      data: { _id: order._id, orderId: order.orderId, status: order.status },
    });
  } catch (err) {
    console.error("[updateOrderStatus]", err);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
};

/**
 * GET /api/order/orderManagement
 * Admin dashboard summary: counts by status + formatted order list.
 * @query page, limit
 * @access Private (Admin)
 */
exports.orderManagement = async (req, res) => {
  try {
    const page = Math.max(1, parseInt(req.query.page, 10) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));
    const skip = (page - 1) * limit;

    const [statusCounts, orders, total] = await Promise.all([
      // Aggregate status breakdown in one DB call
      Order.aggregate([
        { $group: { _id: "$status", count: { $sum: 1 } } },
      ]),
      Order.find()
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .populate("userId", "name email")
        .populate("providerId", "name")
        .lean(),
      Order.countDocuments(),
    ]);

    const counts = statusCounts.reduce((acc, { _id, count }) => {
      acc[_id] = count;
      return acc;
    }, {});

    return res.status(200).json({
      success: true,
      data: {
        summary: {
          totalOrders: total,
          pendingOrders: counts.pending ?? 0,
          acceptedOrders: counts.accepted ?? 0,
          inProgressOrders: counts.in_progress ?? 0,
          readyOrders: counts.ready ?? 0,
          deliveredOrders: counts.delivered ?? 0,
          cancelledOrders: counts.cancelled ?? 0,
        },
        orders: orders.map((order) => ({
          _id: order._id,
          orderId: order.orderId,
          customer: order.userId?.name ?? "N/A",
          dhobi: order.providerId?.name ?? "N/A",
          amount: order.amount,
          status: order.status,
          paymentStatus: order.paymentStatus,
          createdAt: order.createdAt,
        })),
      },
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
        hasNextPage: page * limit < total,
        hasPrevPage: page > 1,
      },
    });
  } catch (err) {
    console.error("[orderManagement]", err);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
};

// ─── Payment ──────────────────────────────────────────────────────────────────

/**
 * POST /api/order/create-razorpay-order
 * Creates a Razorpay payment order for an existing platform order.
 * @access Private (User)
 */
exports.createRazorpayOrder = async (req, res) => {
  try {
    if (!process.env.RAZORPAY_KEY_ID || !process.env.RAZORPAY_KEY_SECRET) {
      console.error("[createRazorpayOrder] Razorpay keys missing from environment");
      return res.status(500).json({ success: false, message: "Payment service is not configured" });
    }

    const { orderId } = req.body;

    if (!orderId?.trim()) {
      return res.status(400).json({ success: false, message: "orderId is required" });
    }

    const order = await Order.findOne({ orderId })
      .populate("userId", "name email mobile")
      .populate("providerId", "name");

    if (!order) {
      return res.status(404).json({ success: false, message: "Order not found" });
    }

    // Authorization: only the order's user can initiate payment
    if (order.userId._id.toString() !== req.user.id.toString()) {
      return res.status(403).json({ success: false, message: "Access denied" });
    }

    if (order.paymentStatus === "completed") {
      return res.status(409).json({ success: false, message: "Payment already completed for this order" });
    }

    if (["cancelled"].includes(order.status)) {
      return res.status(400).json({ success: false, message: "Cannot initiate payment for a cancelled order" });
    }

    // Amount in paise (Razorpay requires integer paise, no floats)
    const amountPaise = Math.round(order.amount * 100);

    const razorpayOrder = await razorpay.orders.create({
      amount: amountPaise,
      currency: "INR",
      receipt: `rcpt_${orderId}_${Date.now()}`.slice(0, 40), // Razorpay receipt max 40 chars
      notes: {
        orderId: order.orderId,
        userId: order.userId._id.toString(),
        providerId: order.providerId._id.toString(),
      },
    });

    // Persist Razorpay order ID for later signature verification
    await Order.findByIdAndUpdate(order._id, { razorpayOrderId: razorpayOrder.id });

    return res.status(201).json({
      success: true,
      data: {
        razorpayOrderId: razorpayOrder.id,
        key: process.env.RAZORPAY_KEY_ID,
        amount: razorpayOrder.amount,
        currency: razorpayOrder.currency,
        order: {
          _id: order._id,
          orderId: order.orderId,
          customerName: order.userId.name,
          customerEmail: order.userId.email,
          customerContact: order.userId.mobile,
        },
      },
    });
  } catch (err) {
    console.error("[createRazorpayOrder]", err);
    const msg = err?.error?.description ?? err?.description ?? err?.message;
    return res.status(err?.statusCode ?? 500).json({
      success: false,
      message: msg ?? "Failed to create payment order",
    });
  }
};

/**
 * POST /api/order/verify-payment
 * Verifies Razorpay signature and marks order as paid.
 * Uses timing-safe comparison to prevent signature forgery.
 * @access Private (User)
 */
exports.verifyPayment = async (req, res) => {
  try {
    const { orderId, razorpayPaymentId, razorpayOrderId, razorpaySignature } = req.body;

    if (!orderId || !razorpayPaymentId || !razorpayOrderId || !razorpaySignature) {
      return res.status(400).json({ success: false, message: "Missing required payment fields" });
    }

    const order = await Order.findOne({ orderId });
    if (!order) {
      return res.status(404).json({ success: false, message: "Order not found" });
    }

    if (order.userId.toString() !== req.user.id.toString()) {
      return res.status(403).json({ success: false, message: "Access denied" });
    }

    if (order.paymentStatus === "completed") {
      return res.status(409).json({ success: false, message: "Payment already verified" });
    }

    // Verify that the razorpayOrderId matches what we stored
    if (order.razorpayOrderId !== razorpayOrderId) {
      return res.status(400).json({ success: false, message: "Razorpay order ID mismatch" });
    }

    // ── Signature verification (timing-safe) ─────────────────────────────────
    const expectedSig = crypto
      .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET)
      .update(`${razorpayOrderId}|${razorpayPaymentId}`)
      .digest("hex");

    const sigValid = crypto.timingSafeEqual(
      Buffer.from(expectedSig),
      Buffer.from(razorpaySignature)
    );

    if (!sigValid) {
      await Order.findByIdAndUpdate(order._id, {
        paymentStatus: "failed",
        failureReason: "Invalid payment signature",
      });
      return res.status(400).json({ success: false, message: "Payment verification failed: invalid signature" });
    }

    // ── Mark order as paid ───────────────────────────────────────────────────
    await Order.findByIdAndUpdate(order._id, {
      paymentStatus: "completed",
      razorpayPaymentId,
      razorpaySignature, // stored with select:false — never returned in responses
      paidAt: new Date(),
    });

    // Notify provider about payment
    const provider = await ServiceProvider.findById(order.providerId).select("userId").lean();
    if (provider?.userId) {
      notify(
        provider.userId,
        `Payment received for order #${order.orderId}.`,
        order._id,
        "order"
      );
    }

    return res.status(200).json({
      success: true,
      message: "Payment verified successfully",
      data: {
        orderId: order.orderId,
        paymentStatus: "completed",
        paidAt: new Date(),
      },
    });
  } catch (err) {
    console.error("[verifyPayment]", err);
    return res.status(500).json({ success: false, message: "Payment verification failed" });
  }
};

/**
 * GET /api/order/payment-status/:orderId
 * Returns the payment status of an order.
 * @access Private
 */
exports.getPaymentStatus = async (req, res) => {
  try {
    const order = await Order.findOne({ orderId: req.params.orderId })
      .select("orderId paymentStatus paidAt amount userId providerId status")
      .lean();

    if (!order) {
      return res.status(404).json({ success: false, message: "Order not found" });
    }

    // Auth: user owns it, or it's their provider order, or admin
    const isAdmin = req.user.role === "admin";
    const isOrderUser = order.userId?.toString() === req.user.id;
    let isOrderProvider = false;
    if (req.user.role === "dhobi") {
      const p = await ServiceProvider.findOne({ userId: req.user.id }).select("_id").lean();
      isOrderProvider = p?._id?.toString() === order.providerId?.toString();
    }

    if (!isAdmin && !isOrderUser && !isOrderProvider) {
      return res.status(403).json({ success: false, message: "Access denied" });
    }

    return res.status(200).json({
      success: true,
      data: {
        orderId: order.orderId,
        amount: order.amount,
        orderStatus: order.status,
        paymentStatus: order.paymentStatus,
        paidAt: order.paidAt ?? null,
      },
    });
  } catch (err) {
    console.error("[getPaymentStatus]", err);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
};

/**
 * POST /api/order/webhook
 * Razorpay webhook handler. Must be mounted BEFORE express.json() on this route
 * so that req.body is the raw buffer for signature verification.
 * @access Public (signature-verified)
 */
exports.handleWebhook = async (req, res) => {
  try {
    const webhookSecret = process.env.RAZORPAY_WEBHOOK_SECRET;
    if (!webhookSecret) {
      console.error("[handleWebhook] RAZORPAY_WEBHOOK_SECRET not set");
      return res.status(500).json({ success: false });
    }

    const webhookSignature = req.get("X-Razorpay-Signature");
    if (!webhookSignature) {
      return res.status(400).json({ success: false, message: "Missing webhook signature" });
    }

    // req.body must be the raw buffer (use express.raw() on this route)
    const rawBody = req.body instanceof Buffer ? req.body : Buffer.from(JSON.stringify(req.body));

    const expectedSig = crypto
      .createHmac("sha256", webhookSecret)
      .update(rawBody)
      .digest("hex");

    const sigValid = crypto.timingSafeEqual(
      Buffer.from(expectedSig),
      Buffer.from(webhookSignature)
    );

    if (!sigValid) {
      console.warn("[handleWebhook] Invalid signature");
      return res.status(400).json({ success: false, message: "Invalid webhook signature" });
    }

    // Parse body only after signature is confirmed
    const payload = JSON.parse(rawBody.toString());
    const event = payload?.event;
    const paymentEntity = payload?.payload?.payment?.entity;
    const orderId = paymentEntity?.notes?.orderId;

    if (!orderId) {
      // Acknowledge unknown events so Razorpay doesn't retry
      return res.status(200).json({ success: true, message: "Event acknowledged (no orderId)" });
    }

    if (event === "payment.captured") {
      await Order.findOneAndUpdate(
        { orderId, paymentStatus: { $ne: "completed" } }, // idempotent
        {
          paymentStatus: "completed",
          razorpayPaymentId: paymentEntity.id,
          paidAt: new Date(),
        }
      );
    } else if (event === "payment.failed") {
      await Order.findOneAndUpdate(
        { orderId, paymentStatus: { $ne: "completed" } }, // don't overwrite a completed payment
        {
          paymentStatus: "failed",
          failureReason: paymentEntity.error_description ?? "Payment failed",
        }
      );
    }
    // All other events acknowledged silently

    return res.status(200).json({ success: true });
  } catch (err) {
    console.error("[handleWebhook]", err);
    // Return 200 to Razorpay to stop retries on unexpected errors
    return res.status(200).json({ success: false, message: "Webhook processing error" });
  }
};

/**
 * POST /api/order/refund
 * Admin initiates a refund via Razorpay. Full or partial.
 * Body: { orderId, amount? (partial), reason? }
 * @access Private (Admin)
 */
exports.refundPayment = async (req, res) => {
  try {
    const { orderId, amount, reason } = req.body;

    if (!orderId?.trim()) {
      return res.status(400).json({ success: false, message: "orderId is required" });
    }

    const order = await Order.findOne({ orderId });
    if (!order) {
      return res.status(404).json({ success: false, message: "Order not found" });
    }

    if (!order.razorpayPaymentId) {
      return res.status(400).json({ success: false, message: "No payment found for this order" });
    }

    if (order.paymentStatus !== "completed") {
      return res.status(400).json({
        success: false,
        message: `Cannot refund an order with payment status "${order.paymentStatus}"`,
      });
    }

    if (order.refundId) {
      return res.status(409).json({ success: false, message: "A refund has already been processed for this order" });
    }

    const refundOptions = {
      notes: { reason: reason?.trim() || "Admin-initiated refund", orderId },
    };

    // Partial refund: validate amount
    if (amount !== undefined) {
      const parsedAmount = Number(amount);
      if (isNaN(parsedAmount) || parsedAmount <= 0 || parsedAmount > order.amount) {
        return res.status(400).json({
          success: false,
          message: `Refund amount must be between 0 and ${order.amount}`,
        });
      }
      refundOptions.amount = Math.round(parsedAmount * 100); // paise
    }

    const refund = await razorpay.payments.refund(order.razorpayPaymentId, refundOptions);

    await Order.findByIdAndUpdate(order._id, {
      refundId: refund.id,
      refundAmount: refund.amount / 100,
      refundStatus: refund.status,
      refundedAt: new Date(),
      paymentStatus: "refunded",
    });

    // Notify the customer
    notify(
      order.userId,
      `Your refund for order #${order.orderId} of ₹${refund.amount / 100} has been initiated.`,
      order._id,
      "order"
    );

    return res.status(200).json({
      success: true,
      message: "Refund processed successfully",
      data: {
        refundId: refund.id,
        refundAmount: refund.amount / 100,
        refundStatus: refund.status,
      },
    });
  } catch (err) {
    console.error("[refundPayment]", err);
    const msg = err?.error?.description ?? err?.description ?? err?.message;
    return res.status(err?.statusCode ?? 500).json({
      success: false,
      message: msg ?? "Refund processing failed",
    });
  }
};
